### PR TITLE
Attempt 64-bit fix

### PR DESCRIPTION
**Pull request by ghost**
Closes gh-2.

### CODE REVIEW

**Comment by ghost** [comment]
@conda-forge-admin Please rerender

**Comment by ghost** [comment]
cc @giacomov

**Comment by ghost** [comment]
Update: this doesn't work.

**Comment by giacomov** [comment]
ok, sorry about that. 

I am a bit surprised about your problem though, f2c has been around for a long time and it has been used on Windows a lot in the past... are you sure it doesn't have to do with your particular setup?

In any case, you might want to write to netlib_maintainers at netlib.org and ask for advice.

Good luck!

**Comment by ghost** [comment]
The problem is that some of the pointers have a different size on 64-bit. I could fix the problem but I have other priorities at this moment. 

> In any case, you might want to write to netlib_maintainers at netlib.org and ask for advice.

They publish 32-bit binaries, which are fine.

**Comment by giacomov** [comment]
ok. Then maybe you can compile at 32 bit on windows? Should be just a flag to add to the compilation in case you are on Windows

**Comment by ghost** [comment]
Yes, I can. However, the vs2015 runtime is architecture specific, so to package we need to compile 64-bit.

**Pull request closed without merging**
